#Name of Service
spring:
  application:
    name: auth-service

server:
  port: 8082

#Eureka Configuration
##vai dar preferencia ao endereco do ip
eureka:
  instance:
    prefer-ip-address: true
##endereco do eureka server
  client:
    service-url: 
       defaultZone: http://localhost:8762/eureka


